Vezba9/SwitchService_WebRole/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwitchService_WebRole.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Vezba9/SwitchService_WebRole/Controllers/SwitchController.cs
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.Queue;
using SwitchService_Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwitchService_WebRole.Controllers
{
    public class SwitchController : Controller
    {
        private SwitchDataRepository repo = new SwitchDataRepository();

        // GET: Switch
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(string Name, string State)
        {
            try
            {
                if (!State.Equals("otvoren") && !State.Equals("zatvoren"))
                {
                    return View("Error");
                }

                CloudQueue queue = QueueHelper.GetQueueReference("vezba");
                queue.AddMessage(new CloudQueueMessage($"{Name}:{State}"));

                return View("Index");
            }
            catch
            {
                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult History(string Name)
        {
            var switches = repo.RetrieveSwitches(Name);

            BlobHelper blobHelper = new BlobHelper();
            CloudBlockBlob blob = blobHelper.GetBlockBlobReference("vezba", "snapshot");

            string text = "";
            foreach (Switch sw in switches)
            {
                text += $"{sw.Name}:{sw.State}$$";
            }
            blobHelper.UploadText(text, blob);

            return View("History", switches);
        }

        public ActionResult Error()
        {
            return View("Error");
        }
    }
}

Vezba9/SwitchService_WebRole/Views/Switch/History.cshtml
@model IEnumerable<SwitchService_Data.Switch>
@{
    ViewBag.Title = "History";
}

<h2>History</h2>

<table border="1" cellpadding="3">
    <tr>
        <th>Name</th>
        <th>State</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Add New Switch", "Index")
</p>

Vezba9/SwitchService_WebRole/Views/Switch/Index.cshtml
@model SwitchService_Data.Switch
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Add", "Switch", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Switch</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.State)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.State)
            @Html.ValidationMessageFor(model => model.State)
        </div>
        <p>
            <input type="submit" value="Add" />
        </p>
    </fieldset>
}

@using (Html.BeginForm("History", "Switch", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Switch</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <p>
            <input type="submit" value="History" />
        </p>
    </fieldset>
}